### ISSUE TITLE
Brainstorm basic character details and personality of the protagonist

### ISSUE THREAD

**Issue by soulerlunar** [NamePendingCo/platformer#6]
The game's protagonist will be the perspective from which the player experiences the game. We must therefore decide some basic details about them to get a sense of their role in the game. This includes, but is not limited to:
* physical description
* gender (or ambiguous presentation)
* name (or lack thereof)
* Silent or snarky (AKA whether they speak or not)
* Dialogue personality

**Comment by NamePendingDan** [comment]
A basic character design has been added to the wiki. It consists of a basic physical design, personality, and a default name.
