### ISSUE TITLE
Brainstorm basic game mechanics

### ISSUE THREAD

**Issue by Repsaj11** [NamePendingCo/platformer#7]
Come up with ideas in a sort of storm of brains, for the basic mechanics of the thing we are creating.

**Comment by soulerlunar** [comment]
We have determined our planned mechanical features for the game and what buttons they should correspond to on both a keyboard and controller. The design information for this can be found [here](https://github.com/NamePendingCo/platformer/wiki/Basic-Game-Mechanics-and-Default-Controls). We also set the few mechanics that are considered core features to the game. Now that these are complete, we can now move forward with more steps of #9 by programming in the initial movement.
