### ISSUE TITLE
Find temporary asset for hero

### ISSUE THREAD

**Issue by Repsaj11** [NamePendingCo/platformer#8]
Pick an asset from the UNITY ASSET STORE, that can fill in for the protagonist for our game.

FIND ME A HERO!

**Comment by soulerlunar** [comment]
We found a [temporary temporary asset for the hero](https://assetstore.unity.com/packages/2d/characters/hero-knight-pixel-art-165188), which will be used until @DeclanTr11 can weigh in on an asset.

**Comment by soulerlunar** [comment]
The Hero Knight asset is *not* the vibe for our temporary asset, so we will pick another one.

**Comment by soulerlunar** [comment]
We will probably make a temporary asset. We have asked art department for concept art, which should probably be an issue? But I'm too lazy to make it at this point.
